### ISSUE TITLE
NotHandler

### ISSUE THREAD

**Issue by ghost** [JuraSciix/ModernEventAPI#1]
You should (please) add it!

**Comment by ghost** [comment]
I think it's better to make it a separate plugin and forget about everything.

**Comment by ghost** [comment]
@hausemaster3734 forget about what?

**Comment by JuraSciix** [comment]
What for? If you are talking about an attribute indicating that the method is not a handler, then there is no need for it. To prevent the method from being considered a handler, just don't mark it with the EventHandler attribute.
